before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    tags:
      - osusergo
      - netgo
      - static_build
    ldflags:
      - -s -w -X github.com/jojomi/rot/cmd.version={{.Version}} -X github.com/jojomi/rot/cmd.commit={{.Commit}} -X github.com/jojomi/rot/cmd.date={{.Date}} -X github.com/jojomi/rot/cmd.builtBy=goreleaser
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }} {{- if .Arm -}} _v{{ .Arm }} {{- end -}}"
    replacements:
      darwin: macos
      linux: linux
      windows: win
      amd64: amd64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: jojomi
    name: rot
  draft: true
  prerelease: auto
source:
  enabled: true